<a href="https://colab.research.google.com/github/Edward-Regalado/data-analysis-with-pandas/blob/main/Cycle_share_data_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import io
import numpy as np
import calendar

In [ ]:
from google.colab import files
upload = files.upload()

Saving station.csv to station (2).csv
Saving trip.csv to trip (1).csv
Saving weather.csv to weather (1).csv

In [ ]:
station = pd.read_csv('./station.csv')
trips = pd.read_csv('./trip.csv', error_bad_lines=False)
weather = pd.read_csv('./weather.csv')

b'Skipping line 50794: expected 12 fields, saw 20\n'

In [ ]:
station

   station_id  ... decommission_date
0       BT-01  ...               NaN
1       BT-03  ...               NaN
2       BT-04  ...               NaN
3       BT-05  ...               NaN
4      CBD-03  ...               NaN
5      CBD-04  ...               NaN
6      CBD-05  ...               NaN
7      CBD-06  ...               NaN
8      CBD-07  ...               NaN
9      CBD-13  ...               NaN
10      CD-01  ...          8/9/2016
11      CH-01  ...               NaN
12      CH-02  ...               NaN
13      CH-03  ...               NaN
14      CH-05  ...               NaN
15      CH-06  ...               NaN
16      CH-07  ...               NaN
17      CH-08  ...               NaN
18      CH-09  ...               NaN
19      CH-12  ...               NaN
20      CH-15  ...               NaN
21     DPD-01  ...               NaN
22     DPD-03  ...               NaN
23      EL-01  ...               NaN
24      EL-03  ...               NaN
25      EL-05  ...               NaN
26      FH-01  ...         3/18/2016
27      FH-04  ...               NaN
28      ID-04  ...               NaN
29      PS-04  ...               NaN
30      PS-05  ...               NaN
31     SLU-01  ...               NaN
32     SLU-02  ...               NaN
33     SLU-04  ...               NaN
34     SLU-07  ...               NaN
35     SLU-15  ...               NaN
36     SLU-16  ...               NaN
37     SLU-17  ...               NaN
38     SLU-18  ...          7/2/2016
39     SLU-19  ...               NaN
40     SLU-20  ...               NaN
41     SLU-21  ...               NaN
42      UD-01  ...               NaN
43      UD-02  ...               NaN
44      UD-04  ...               NaN
45      UD-07  ...               NaN
46      UW-01  ...        10/29/2015
47      UW-02  ...               NaN
48      UW-04  ...               NaN
49      UW-06  ...               NaN
50      UW-07  ...               NaN
51      UW-10  ...               NaN
52      WF-01  ...               NaN
53      WF-04  ...               NaN
54      CH-16  ...               NaN
55     SLU-22  ...               NaN
56      UW-11  ...               NaN
57      WF-03  ...               NaN

[58 rows x 9 columns]

In [ ]:
## 1. Average Trip Duration for borrowed bicycle
avg_trip_dur = str(round(trips['tripduration'].mean()/60, 2)).split('.')
avg_trip_dur[1] = str(round((60*int(avg_trip_dur[1])/100)))
f"The average trip duration for a borrowed bike is {avg_trip_dur[0]}:{avg_trip_dur[1]}!"

'The average trip duration for a borrowed bike is 19:38!'

In [ ]:
## 2. Most common age of a bicyle sharer
most_common_bike_year = 2021 - int(trips['birthyear'].mode())
f'The most common age of of a bicycle sharer is {most_common_bike_year}.'

'The most common age of of a bicycle sharer is 34.'

In [ ]:
## 3. Find the average precipitation per month, and the median precipitation.
average_precip = weather[['Date', 'Precipitation_In']]
precip_data = []
for i in range(12):
  month_data = [row.Precipitation_In for row in average_precip.iloc if int(row.Date.split('/')[0]) == i+1]
  month_data = np.array(month_data)
  precip_data.append(f'{calendar.month_abbr[i+1]} - mean precipitation: {round(np.mean(month_data), 2)} inches / median precipitation: {np.median(month_data)} inches')

precip_data

['Jan - mean precipitation: 0.14 inches / median precipitation: 0.02 inches',
 'Feb - mean precipitation: 0.17 inches / median precipitation: 0.04 inches',
 'Mar - mean precipitation: 0.16 inches / median precipitation: 0.025 inches',
 'Apr - mean precipitation: 0.05 inches / median precipitation: 0.0 inches',
 'May - mean precipitation: 0.01 inches / median precipitation: 0.0 inches',
 'Jun - mean precipitation: 0.03 inches / median precipitation: 0.0 inches',
 'Jul - mean precipitation: 0.01 inches / median precipitation: 0.0 inches',
 'Aug - mean precipitation: 0.02 inches / median precipitation: 0.0 inches',
 'Sep - mean precipitation: 0.04 inches / median precipitation: 0.0 inches',
 'Oct - mean precipitation: 0.19 inches / median precipitation: 0.04 inches',
 'Nov - mean precipitation: 0.19 inches / median precipitation: 0.035 inches',
 'Dec - mean precipitation: 0.24 inches / median precipitation: 0.1 inches']

In [ ]:
## 4. What's the average number of bike at a given bike station?
average_bike = round(station['current_dockcount'].mean())
f'The average number of Bikes at a bike station is {average_bike}.'

'The average number of Bikes at a bike station is 17.'

In [ ]:
## 5. When a bike station is modified, is it more likely that it'll lose bikes or gain bikes? How do you know?
mod_dockcount = round(station[['name', 'install_dockcount', 'current_dockcount', 'modification_date']].sort_values('modification_date').mean())

# print iloc(integer location from index 0-2)
a = mod_dockcount.iloc[0:2]
column = pd.DataFrame(a, columns=['Modified Dockcounts gain bikes on average'])
column

                   Modified Dockcounts gain bikes on average
install_dockcount                                       18.0
current_dockcount                                       17.0